Project_PRN_Razor/Pages/Admin/EnrollmentPages/ClassDetail.cshtml.cs
using System.Security.Claims;
using AutoMapper;
using ClosedXML.Excel;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.EnrollmentPages;

[Authorize(Roles = "Admin")]
public class ClassDetail : PageModel
{
    private ISemesterRepository _semesterRepository;
    private ISubjectRepository _subjectRepository;
    private IClassRepository _classRepository;
    private IEnrollmentRepository _enrollmentRepository;
    private IMarkReportRepository _markReportRepository;
    private IMarkRepository _markRepository;
    
    [BindProperty]
    public SemesterDto? SelectedSemester { get; set; }
    [BindProperty]
    public SubjectDto? SelectedSubject { get; set; }
    [BindProperty]
    public ClassDto? SelectedClass { get; set; }
    
    private IMapper _mapper;

    [BindProperty]
    public List<EnrollmentForClassList> EnrollmentList { get; set; }
    
    [BindProperty]
    public List<List<MarkReportDto>> MarkReportList { get; set; }

    [BindProperty]
    public List<string> MarkNameList { get; set; }
    public ClassDetail(ISemesterRepository semesterRepository, ISubjectRepository subjectRepository, IClassRepository classRepository, IEnrollmentRepository enrollmentRepository, IMarkReportRepository markReportRepository, IMarkRepository markRepository, IMapper mapper)
    {
        _semesterRepository = semesterRepository;
        _subjectRepository = subjectRepository;
        _classRepository = classRepository;
        _enrollmentRepository = enrollmentRepository;
        _markReportRepository = markReportRepository;
        _markRepository = markRepository;
        _mapper = mapper;
    }
    
    public void OnGet(int selectedSemesterId, int selectedSubjectId, int selectedClassId)
    {
        SelectedClass = _classRepository.GetClassById(selectedClassId);
        SelectedSemester = _semesterRepository.GetSemesterById(selectedSemesterId);
        SelectedSubject = _subjectRepository.GetSubjectById(selectedSubjectId);
        EnrollmentList = _enrollmentRepository.GetClassDetailByAdmin( selectedSemesterId, selectedSubjectId, selectedClassId);
        MarkReportList = new List<List<MarkReportDto>>();
        for (var i = 0; i < EnrollmentList.Count; i++)
        {
            var markList = _markReportRepository.GetMarkReportByEnrollmentId(EnrollmentList[i].EnrollmentId);
            MarkReportList.Add(markList.Select(x => new MarkReportDto
            {
                MarkId = x.MarkId,
                MarkName = x.Mark.MarkName,
                MarkValue = x.MarkValue,
                Coefficient = x.Mark.Coefficient * 100 + "%"
            }).ToList());
        }

        MarkNameList = new List<string>();
        var subjectDetail = _subjectRepository.GetSubjectDetailById(SelectedSubject.SubjectId);
        foreach (var mark in subjectDetail.MarkList)
        {
            MarkNameList.Add(mark.Mark.MarkName);
        }
    }

    public IActionResult OnPostGetTemplate(int selectedSemesterId, int selectedSubjectId, int selectedClassId)
    {
        SelectedClass = _classRepository.GetClassById(selectedClassId);
        SelectedSemester = _semesterRepository.GetSemesterById(selectedSemesterId);
        SelectedSubject = _subjectRepository.GetSubjectById(selectedSubjectId);
        EnrollmentList = _enrollmentRepository.GetClassDetail(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), selectedSemesterId, selectedSubjectId, selectedClassId);

        var workBook = BuildTemplate();
        using MemoryStream streamWriter = new MemoryStream();
        workBook.SaveAs(streamWriter);

        return File(streamWriter.ToArray(),  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "templateMark.xlsx");
        //return Page();
    }
    

    private XLWorkbook BuildTemplate()
    {
        var subjectDetail = _subjectRepository.GetSubjectDetailById(SelectedSubject.SubjectId);

        var workbook = new XLWorkbook();
        var ws = workbook.Worksheets.Add("Mark Report");

        int row = 1, column = 1;
        
        ws.Cell(row, column).Value = "Student Code";
        column++;

        ws.Cell(row, column).Value = "Student name";
        column++;

        foreach (var mark in subjectDetail.MarkList)
        {
            ws.Cell(row, column).Value = mark.Mark.MarkName;
            column++;
        }

        foreach (var enroll in EnrollmentList)
        {
            var markDetailList = _markReportRepository.GetMarkReportByEnrollmentId(enroll.EnrollmentId);
            row++;
            column = 1;
            ws.Cell(row, column).Value = enroll.StudentCode;
            column++;
            
            ws.Cell(row, column).Value = enroll.StudentName;
            column++;

            foreach (var mark in markDetailList)
            {
                ws.Cell(row, column).Value = mark.MarkValue;
                column++;
            }

        }

        return workbook;
    }

    

    
}

Project_PRN_Razor/Pages/Admin/EnrollmentPages/EnrollmentDetail.cshtml.cs
using AutoMapper;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.EnrollmentPages;

[Authorize(Roles = "Admin")]
public class EnrollmentDetail : PageModel
{
    private IEnrollmentRepository _enrollmentRepository;
    private ISubjectRepository _subjectRepository;
    private IMarkReportRepository _markReportRepository;
    private IMapper _mapper;
    
    public EnrollmentDto EnrollmentModel { get; set; }
    [BindProperty]
    public List<MarkReportDto> MarkList { get; set; }


    public EnrollmentDetail(IEnrollmentRepository enrollmentRepository, ISubjectRepository subjectRepository, IMarkReportRepository markReportRepository, IMapper mapper)
    {
        _enrollmentRepository = enrollmentRepository;
        _subjectRepository = subjectRepository;
        _markReportRepository = markReportRepository;
        _mapper = mapper;
    }   
    
    public void OnGet(int enrollmentId)
    {
        EnrollmentModel = _enrollmentRepository.GetEnrollmentDetail(enrollmentId);
        var markList = _markReportRepository.GetMarkReportByEnrollmentId(enrollmentId);
        MarkList = markList.Select(x => new MarkReportDto
        {
            MarkId = x.MarkId,
            MarkName = x.Mark.MarkName,
            MarkValue = x.MarkValue,
            Coefficient = x.Mark.Coefficient * 100 + "%"
        }).ToList();
    }

    public IActionResult OnPost(int enrollmentId)
    {
        foreach (var mark in MarkList)
        {
            _markReportRepository.UpdateMarkValue(enrollmentId, mark.MarkId, mark.MarkValue);
        }
        _enrollmentRepository.UpdateFinalMark(enrollmentId);
        return RedirectToPage("EnrollmentDetail",new{enrollmentId = enrollmentId});
    }
}

Project_PRN_Razor/Pages/Teacher/ClassDetail.cshtml.cs
using System.Security.Claims;
using AutoMapper;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Teacher;
[Authorize(Roles = "Teacher")]
public class ClassDetail : PageModel
{
    private ISemesterRepository _semesterRepository;
    private ISubjectRepository _subjectRepository;
    private IClassRepository _classRepository;
    private IEnrollmentRepository _enrollmentRepository;

    public SemesterDto? SelectedSemester { get; set; }
    public SubjectDto? SelectedSubject { get; set; }
    public ClassDto? SelectedClass { get; set; }
    
    private IMapper _mapper;

    public List<EnrollmentForClassList> EnrollmentList { get; set; }
    public ClassDetail(ISemesterRepository semesterRepository, ISubjectRepository subjectRepository, IClassRepository classRepository, IEnrollmentRepository enrollmentRepository, IMapper mapper)
    {
        _semesterRepository = semesterRepository;
        _subjectRepository = subjectRepository;
        _classRepository = classRepository;
        _enrollmentRepository = enrollmentRepository;
        _mapper = mapper;
    }
    
    public void OnGet(int selectedSemesterId, int selectedSubjectId, int selectedClassId)
    {
        SelectedClass = _classRepository.GetClassById(selectedClassId);
        SelectedSemester = _semesterRepository.GetSemesterById(selectedSemesterId);
        SelectedSubject = _subjectRepository.GetSubjectById(selectedSubjectId);
        EnrollmentList = _enrollmentRepository.GetClassDetail(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), selectedSemesterId, selectedSubjectId, selectedClassId);
    }
}

Project_PRN_Razor/Pages/Teacher/EnrollmentDetail.cshtml.cs
using AutoMapper;
using Domain.Models;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Teacher;
[Authorize(Roles = "Teacher")]
public class EnrollmentDetail : PageModel
{
    private IEnrollmentRepository _enrollmentRepository;
    private ISubjectRepository _subjectRepository;
    private IMarkReportRepository _markReportRepository;
    private IMapper _mapper;
    
    public EnrollmentDto EnrollmentModel { get; set; }
    [BindProperty]
    public List<MarkReportDto> MarkList { get; set; }


    public EnrollmentDetail(IEnrollmentRepository enrollmentRepository, ISubjectRepository subjectRepository, IMarkReportRepository markReportRepository, IMapper mapper)
    {
        _enrollmentRepository = enrollmentRepository;
        _subjectRepository = subjectRepository;
        _markReportRepository = markReportRepository;
        _mapper = mapper;
    }   
    
    public void OnGet(int enrollmentId)
    {
        EnrollmentModel = _enrollmentRepository.GetEnrollmentDetail(enrollmentId);
        var markList = _markReportRepository.GetMarkReportByEnrollmentId(enrollmentId);
        MarkList = markList.Select(x => new MarkReportDto
        {
            MarkId = x.MarkId,
            MarkName = x.Mark.MarkName,
            MarkValue = x.MarkValue,
            Coefficient = x.Mark.Coefficient * 100 + "%"
        }).ToList();
    }

    public IActionResult OnPost(int enrollmentId)
    {
        foreach (var mark in MarkList)
        {
            _markReportRepository.UpdateMarkValue(enrollmentId, mark.MarkId, mark.MarkValue);
        }
        _enrollmentRepository.UpdateFinalMark(enrollmentId);
        return RedirectToPage("EnrollmentDetail",new{enrollmentId = enrollmentId});
    }
}

Project_PRN_Razor/Pages/Teacher/Index.cshtml.cs
using System.Security.Claims;
using AutoMapper;
using Domain.Constants;
using Domain.Models;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Teacher;
[Authorize(Roles = "Teacher")]
public class Index : PageModel
{
    private ISemesterRepository _semesterRepository;
    private ISubjectRepository _subjectRepository;
    private IClassRepository _classRepository;
    private IEnrollmentRepository _enrollmentRepository;
    private IMapper _mapper;
    
    public IEnumerable<SemesterDto> Semesters { get; set; }
    public IEnumerable<SubjectDto> Subjects { get; set; }
    public IEnumerable<ClassDto> Classes { get; set; }
    
    public SemesterDto? SelectedSemester { get; set; }
    public SubjectDto? SelectedSubject { get; set; }
    
    public int? SelectedSemesterId { get; set; }
    public int? SelectedSubjectId { get; set; }
    
    public string? TeacherAccountId { get; set; }

    public Index(IMapper mapper, ISemesterRepository semesterRepository, ISubjectRepository subjectRepository, IClassRepository classRepository, IEnrollmentRepository enrollmentRepository)
    {
        _semesterRepository = semesterRepository;
        _subjectRepository = subjectRepository;
        _classRepository = classRepository;
        _enrollmentRepository = enrollmentRepository;
        _mapper = mapper;
    }   
    public void OnGet()
    {
        Semesters = _semesterRepository.GetAllSemester().Where(x => x.Deleted.Equals(Common.Status.Active));
        TeacherAccountId = User.FindFirstValue(ClaimTypes.Sid);
    }

    public IActionResult OnPostLoadSubject(int selectedSemesterId)
    {
        Semesters = _semesterRepository.GetAllSemester().Where(x => x.Deleted.Equals(Common.Status.Active));
        TeacherAccountId = User.FindFirstValue(ClaimTypes.Sid);
        SelectedSemesterId = selectedSemesterId;
        var subjectIdList = _enrollmentRepository.GetSubjectIdListByTeacher(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), selectedSemesterId);
        Subjects = _subjectRepository.GetAllSubjects().Where(x => subjectIdList.Contains(x.SubjectId));
        //return RedirectToPage("Index");
        //return JsonResult(Subjects);
        return Page();
    }

    public IActionResult OnPostLoadClass(int selectedSemesterId, int selectedSubjectId)
    {
        Semesters = _semesterRepository.GetAllSemester().Where(x => x.Deleted.Equals(Common.Status.Active));
        SelectedSemesterId = selectedSemesterId;
        TeacherAccountId = User.FindFirstValue(ClaimTypes.Sid);
        var subjectIdList = _enrollmentRepository.GetSubjectIdListByTeacher(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), selectedSemesterId);
        Subjects = _subjectRepository.GetAllSubjects().Where(x => subjectIdList.Contains(x.SubjectId));
        SelectedSubjectId = selectedSubjectId;
        var classIdList = _enrollmentRepository.GetClassIdListByTeacher(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), selectedSemesterId, selectedSubjectId);
        Classes = _classRepository.GetAllClasses().Where(x => classIdList.Contains(x.ClassId));
        return Page();
    }
    
    
}

Project_PRN_Razor/Pages/Teacher/ClassDetail.cshtml
@page "{selectedSemesterId:int}/{selectedSubjectId:int}/{selectedClassId:int}"
@using Project_PRN_Razor.Pages.Shared
@model Project_PRN_Razor.Teacher.ClassDetail

@{
    Layout = "Shared/_LayoutTeacher";
}
@if (Model.ViewData["Message"] != null)
{
    <h1>@Model.ViewData["Message"]</h1>
}
<h1></h1>
<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">@Model.SelectedClass.ClassName - @Model.SelectedSemester.SemesterName - @Model.SelectedSubject.SubjectName</h2>
    </div>
    <div class="col-6">
    </div>
</div>
<div style="display: flex; margin-top: 40px;">
    <div style="display: flex">
        <form method="post" enctype="multipart/form-data" style="display: flex">
            <div class="form-group">
                <input name="selectedSemesterId" value="@Model.SelectedSemester.SemesterId" type="hidden"/>
                <input name="selectedSubjectId" value="@Model.SelectedSubject.SubjectId" type="hidden"/>
                <input name="selectedClassId" value="@Model.SelectedClass.ClassId" type="hidden"/>
                <input type="file" class="form-control-file" id="fileInput" name="importFile">
            </div>
            <button type="submit" class="btn btn-primary" asp-page-handler="ImportMark" style="margin-left: 10px">Import</button>
        </form>
    </div>

    <div>
        <form method="post" style="margin-left: 10px">
            <input name="selectedSemesterId" value="@Model.SelectedSemester.SemesterId" type="hidden"/>
            <input name="selectedSubjectId" value="@Model.SelectedSubject.SubjectId" type="hidden"/>
            <input name="selectedClassId" value="@Model.SelectedClass.ClassId" type="hidden"/>
            <button type="submit" asp-page-handler="GetTemplate" class="btn btn-info">Download mark template</button>
        </form>
    </div>

</div>
<br/><br/>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">Student Code</th>
        <th scope="col">Student name</th>
        @foreach (var name in @Model.MarkNameList)
        {
            <th scope="col">@name</th>
        }
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @for (var i = 0 ; i<Model.EnrollmentList.Count; i++)
    {
        <tr>
            <th scope="row">@Model.EnrollmentList[i].StudentCode</th>
            <td>@Model.EnrollmentList[i].StudentName</td>
            @foreach (var mark in @Model.MarkReportList[i])
            {
                <td>@mark.MarkValue</td>
            }
            <td>

                <a href="/Teacher/EnrollmentDetail/@Model.EnrollmentList[i].EnrollmentId" class="btn btn-primary">Detail</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Project_PRN_Razor/Pages/Teacher/EnrollmentDetail.cshtml
@page "{enrollmentId:int}"
@using Project_PRN_Razor.Pages.Shared
@model Project_PRN_Razor.Teacher.EnrollmentDetail

@{
    Layout = "Shared/_LayoutTeacher";
}

<div class="container" style="margin-top: 100px;">
    <h3 class="font-weight-bold">Mark report</h3>
    <div class="row" style="margin-top: 30px">
        <div class="col-6">
            <div class="card border-info mb-3" style="max-width: 20rem;">
                <div class="card-header">Mark Report</div>
                <div class="card-body">
                    <p class="text-dark">Semester: @Model.EnrollmentModel.Semester.SemesterName</p>
                    <p class="text-dark">Student Code: @Model.EnrollmentModel.StudentCode</p>
                    <p class="text-dark">Student name: @Model.EnrollmentModel.StudentName</p>
                    <p class="text-dark">Class: @Model.EnrollmentModel.Class.ClassName</p>
                    <p class="text-dark">Subject:@Model.EnrollmentModel.Subject.SubjectCode-@Model.EnrollmentModel.Subject.SubjectName</p>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row" style="margin-bottom: 20px">
                <div class="col-3 font-weight-bold">
                    Mark name
                </div>
                <div class="col-2 font-weight-bold">
                    Weight
                </div>
                <div class="col-2 font-weight-bold">
                    Value
                </div>
            </div>

            <form method="post" id="myForm">
                <div class="form-group">
                    <input name="enrollmentId" value="@Model.EnrollmentModel.EnrollmentId" type="hidden">
                    @for (var i = 0; i < @Model.MarkList.Count; i++)
                    {
                        <input name="MarkList[@i].MarkId" value="@Model.MarkList[i].MarkId" type="hidden">
                        <input name="MarkList[@i].MarkName" value="@Model.MarkList[i].MarkName" type="hidden">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-3">
                                    <label class="control-label">@Model.MarkList[i].MarkName</label>
                                </div>
                                <div class="col-2">
                                    <label class="control-label">@Model.MarkList[i].Coefficient</label>
                                </div>
                                <div class="col-2">
                                    <input type="number" step="0.01" min="0" max="10" class="form-control mark-input" name="MarkList[@i].MarkValue" placeholder="Value" value="@Model.MarkList[i].MarkValue" required>
                                    <div class="invalid-feedback">
                                        mark value in [0,10]
                                    </div>
                                </div>
                            </div>


                        </div>
                    }
                </div>
                <h5 class="text-dark" style="margin-top: 20px">Average: @Model.EnrollmentModel.FinalMark</h5>
                @if (Model.EnrollmentModel.Status)
                {
                    <h5 class="text-success">Pass</h5>
                }
                else
                {
                    <h5 class="text-danger">Not pass</h5>
                }
                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
            </form>
        </div>
    </div>
</div>


<br/> <br/>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myForm").submit(function (event) {
            var invalidInputs = $(".mark-input").filter(function () {
                var value = parseFloat($(this).val());
                return isNaN(value) || value < 0 || value > 10;
            });

            if (invalidInputs.length > 0) {
                event.preventDefault();
                invalidInputs.addClass("is-invalid");
            }
        });

        $(".mark-input").on("input", function () {
            var value = parseFloat($(this).val());
            if (isNaN(value) || value < 0 || value > 10) {
                $(this).addClass("is-invalid");
            } else {
                $(this).removeClass("is-invalid");
            }
        });
    });
</script>


@*<form method="post">
    <div id="inputContainer">
        @for (var i = 0; i < @Model.MarkList.Count; i++)
        {
            <input name="enrollmentId" value="@Model.EnrollmentModel.EnrollmentId" type="hidden">
            <input name="MarkList[@i].MarkId" value="@Model.MarkList[i].MarkId" type="hidden">
            <input name="MarkList[@i].MarkName" value="@Model.MarkList[i].MarkName" type="hidden">
            <div class="form-group">
                <label>@Model.MarkList[i]</label>
                <input class="form-control" name="MarkList[@i].MarkValue" placeholder="Value" value="@Model.MarkList[i].MarkValue">
            </div>
        }
    </div>


    <button type="submit" class="btn btn-primary" style="width: 150px; margin-top: 30px;"> Save</button>
</form>*@


@*<form id="myForm" class="form-horizontal">
    <div class="form-group">
        @for (var i = 0; i < @Model.MarkList.Count; i++)
        {
            <input name="enrollmentId" value="@Model.EnrollmentModel.EnrollmentId" type="hidden">
            <input name="MarkList[@i].MarkId" value="@Model.MarkList[i].MarkId" type="hidden">
            <input name="MarkList[@i].MarkName" value="@Model.MarkList[i].MarkName" type="hidden">
            <div class="form-group">
                <label class="control-label col-sm-3">@Model.MarkList[i]</label>
                <input type="number" step="0.01" min="0" max="10" class="form-control mark-input" name="MarkList[@i].MarkValue" placeholder="Value" value="@Model.MarkList[i].MarkValue" required>
                <div class="invalid-feedback">
                    Giá trị phải nằm trong khoảng từ 0 đến 10.
                </div>
            </div>
        }
    </div>


    <button type="submit" class="btn btn-primary" id="submitButton">Gửi</button>
</form>

<script>
    $(document).ready(function () {
        $("#myForm").submit(function (event) {
            var invalidInputs = $(".mark-input").filter(function () {
                var value = parseFloat($(this).val());
                return isNaN(value) || value < 0 || value > 10;
            });

            if (invalidInputs.length > 0) {
                event.preventDefault();
                invalidInputs.addClass("is-invalid");
            }
        });

        $(".mark-input").on("input", function () {
            var value = parseFloat($(this).val());
            if (isNaN(value) || value < 0 || value > 10) {
                $(this).addClass("is-invalid");
            } else {
                $(this).removeClass("is-invalid");
            }
        });
    });
</script>*@

Project_PRN_Razor/Pages/Teacher/Index.cshtml
@page
@using Project_PRN_Razor.Pages.Shared
@model Project_PRN_Razor.Teacher.Index

@{
    Layout = "Shared/_LayoutTeacher";
}

<div class="container" style="margin-top: 30px;">
    <div class="row">
        <div class="col-4">
            <h3 class="text-primary">Semester</h3>
            <ul class="list-group">
                @foreach (var semester in Model.Semesters)
                {
                    <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                        <form method="post">
                            <input asp-for="SelectedSemesterId" value="@semester.SemesterId" type="hidden"/>
                            <button type="submit" class="btn btn-primary" asp-page-handler="LoadSubject">@semester.SemesterName</button>
                        </form>
                        @*<button type="button" class="btn btn-primary" onclick="selectSemester(@semester.SemesterId)">@semester.SemesterName</button>*@
                    </li>
                }
            </ul>
        </div>
        <div class="col-4">
            <h3 class="text-primary">Subject</h3>
            @if (Model.Subjects != null)
            {
                <ul class="list-group">
                    @foreach (var subject in Model.Subjects)
                    {
                        <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                            <form method="post">
                                <input asp-for="SelectedSemesterId" value="@Model.SelectedSemesterId" type="hidden"/>
                                <input asp-for="SelectedSubjectId" value="@subject.SubjectId" type="hidden"/>
                                <button type="submit" class="btn btn-primary" asp-page-handler="LoadClass">@subject.SubjectName</button>
                            </form>
                            @*<button type="button" class="btn btn-primary" onclick="selectSemester(@semester.SemesterId)">@semester.SemesterName</button>*@
                        </li>
                    }
                </ul>
            }
        </div>
        <div class="col-4">
            <h3 class="text-primary">Class</h3>
            @if (Model.Classes != null)
            {
                <ul class="list-group">
                    @foreach (var classs in Model.Classes)
                    {
                        <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                            <a class="btn btn-primary" href="/Teacher/ClassDetail/@Model.SelectedSemesterId/@Model.SelectedSubjectId/@classs.ClassId">@classs.ClassName</a>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</div>