Project_PRN_Razor/Pages/Admin/SubjectPages/CreateSubject.cshtml.cs
using AutoMapper;
using Domain.Constants;
using Domain.Models;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.SubjectPages;
[Authorize(Roles = "Admin")]
public class CreateSubject : PageModel
{
    private ISubjectRepository _subjectRepository;
    private IMapper _mapper;
    public SubjectDto Subject { get; set; }

    public CreateSubject(ISubjectRepository subjectRepository, IMapper mapper)
    {
        _subjectRepository = subjectRepository;
        _mapper = mapper;
    }
    public void OnGet()
    {
        
    }

    public IActionResult OnPost(SubjectDto subject)
    {
        subject.SubjectId = _subjectRepository.GetNextId();
        subject.Deleted = Common.Status.Active;
        subject.MarkAvailable = Common.AvailableStatus.UnAvailable;
        _subjectRepository.AddSubject(subject);
        return RedirectToPage("Index");
    }
}

Project_PRN_Razor/Pages/Admin/SubjectPages/DetailSubject.cshtml.cs
using AutoMapper;
using Domain.Constants;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.SubjectPages;
[Authorize(Roles = "Admin")]
public class DetailSubject : PageModel
{
    private ISubjectRepository _subjectRepository;
    private IMarkRepository _markRepository;
    private ISubjectMarkRepository _subjectMarkRepository;
    private IMapper _mapper;
    
    public SubjectDetailDto? Subject { get; set; }
    public IEnumerable<MarkDto> MarkList { get; set; }
    public int SelectedMarkId { get; set; }
    public int SelectedSubjectId { get; set; }

    public DetailSubject(ISubjectRepository subjectRepository, IMarkRepository markRepository, ISubjectMarkRepository subjectMarkRepository, IMapper mapper)
    {
        _subjectRepository = subjectRepository;
        _markRepository = markRepository;
        _subjectMarkRepository = subjectMarkRepository;
        _mapper = mapper;
    }
    
    public void OnGet(int subjectId)
    {
        Subject = _subjectRepository.GetSubjectDetailById(subjectId);
        var addedMarkList = Subject.MarkList.Select(subjectMark => subjectMark.MarkId).ToList();
        MarkList = _markRepository.GetAllMarks().Where(x => x.Deleted.Equals(Common.Status.Active) && !addedMarkList.Contains(x.MarkId));
    }

    public IActionResult OnPostAddMark(int selectedSubjectId, int selectedMarkId)
    {
        if (selectedSubjectId != 0 && selectedMarkId != 0)
        {
            _subjectRepository.AddMarkToSubject(selectedSubjectId, selectedMarkId);   
        }
        return RedirectToPage("DetailSubject", new {id = selectedSubjectId});
    }

    public IActionResult OnPostDeleteMark(int selectedSubjectId, int selectedMarkId)
    {
        if (selectedSubjectId != 0 && selectedMarkId != 0)
        {
            _subjectRepository.DeleteMarkToSubject(selectedSubjectId, selectedMarkId);
        }

        return RedirectToPage("DetailSubject", new { id = selectedSubjectId});
    }

    public IActionResult OnPostApply(int selectedSubjectId)
    {
        if (selectedSubjectId != 0)
        {
            _subjectRepository.ApplySubject(selectedSubjectId);
        }
        return RedirectToPage("DetailSubject", new { id = selectedSubjectId});
    }
}

Project_PRN_Razor/Pages/Admin/SubjectPages/EditSubject.cshtml.cs
using AutoMapper;
using Domain.Constants;
using Infrastructure.Dtos;
using Infrastructure.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.SubjectPages;
[Authorize(Roles = "Admin")]
public class EditSubject : PageModel
{
    private ISubjectRepository _subjectRepository;
    private IMapper _mapper;
    public SubjectDto? Subject { get; set; }
    public IEnumerable<SubjectDto> Subjects { get; set; }

    public EditSubject(ISubjectRepository subjectRepository, IMapper mapper)
    {
        _subjectRepository = subjectRepository;
        _mapper = mapper;
    }
    public void OnGet(int subjectId)
    {
        Subject = _subjectRepository.GetSubjectById(subjectId);
        Subjects = _subjectRepository.GetAllSubjects().Where(x => x.Deleted.Equals(Common.Status.Active));
    }
    public IActionResult OnPostUpdate(SubjectDto subject)
    {
        _subjectRepository.UpdateSubject(subject);
        return RedirectToPage("Index");
    }

    public IActionResult OnPostDelete(SubjectDto subject)
    {
        _subjectRepository.DeleteSubject(subject.SubjectId);
        return RedirectToPage("Index");
    }
}

Project_PRN_Razor/Pages/Admin/SubjectPages/Index.cshtml.cs
using AutoMapper;
using Domain.Constants;
using Infrastructure.IRepositories;
using Domain.Models;
using Infrastructure.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Project_PRN_Razor.Pages.Admin.SubjectPages;
[Authorize(Roles = "Admin")]
public class Index : PageModel
{
    private ISubjectRepository _subjectRepository;
    private IMapper _mapper;
    public IEnumerable<SubjectDto> Subjects;

    public Index(ISubjectRepository subjectRepository, IMapper mapper)
    {
        _subjectRepository = subjectRepository;
        _mapper = mapper;
    }
    public void OnGet()
    {
        var subjectList = _subjectRepository.GetAllSubjects().Where(x => x.Deleted.Equals(Common.Status.Active));
        Subjects = _mapper.Map<IEnumerable<SubjectDto>>(subjectList);
    }
}

Project_PRN_Razor/Pages/Admin/SubjectPages/CreateSubject.cshtml
@page
@model Project_PRN_Razor.Pages.Admin.SubjectPages.CreateSubject

@{
    Layout = "Shared/_LayoutAdmin";
}

<form method="post">
    <div class="form-group">
        <label asp-for="Subject.SubjectName">Subject name</label>
        <input asp-for="Subject.SubjectName" class="form-control" placeholder="name">
    </div>
    <div class="form-group">
        <label asp-for="Subject.SubjectCode">Subject Code</label>
        <input asp-for="Subject.SubjectCode" class="form-control" placeholder="Code">
    </div>

    <button type="submit" class="btn btn-primary" style="width: 150px; margin-top: 30px;"> Create</button>
</form>

Project_PRN_Razor/Pages/Admin/SubjectPages/DetailSubject.cshtml
@page "{subjectId:int}"
@using Domain.Constants
@model Project_PRN_Razor.Pages.Admin.SubjectPages.DetailSubject

@{
    Layout = "Shared/_LayoutAdmin";
}

<div class="card w-75">
    <div class="card-body">
        <h5 class="card-title">@Model.Subject.SubjectName</h5>
        <table class="card-body table table-bordered">
            <thead>
            <tr>
                <th scope="col">Mark Name</th>
                <th scope="col">Coefficient</th>
                @if (!Model.Subject.Applied)
                {
                    <th scope="col"></th>
                }
            </tr>
            </thead>
            <tbody>
            @foreach (var mark in Model.Subject.MarkList)
            {
                <tr>
                    <td>@mark.Mark.MarkName</td>
                    <td>@mark.Mark.Coefficient</td>
                    @if (!Model.Subject.Applied)
                    {
                        <td>
                            <form method="post">
                                <input asp-for="SelectedSubjectId" value="@Model.Subject.SubjectId" type="hidden"/>
                                <input asp-for="SelectedMarkId" value="@mark.MarkId" type="hidden"/>
                                <button type="submit" asp-page-handler="DeleteMark" style="width:150px" class="btn btn-primary">Delete</button>
                            </form>
                        </td>
                    }
                </tr>
            }
            </tbody>
        </table>
        @if (Model.Subject.Applied)
        {
            <p class="text-success" style="margin-top: 30px">This subject has been applied!</p>
        }
        else
        {
            <form method="post">
                <input asp-for="SelectedSubjectId" value="@Model.Subject.SubjectId" type="hidden"/>
                <div class="form-group">
                    <label asp-for="SelectedMarkId">Add new mark: </label>
                    <select class="form-select" asp-for="SelectedMarkId">
                        @foreach (var mark in Model.MarkList)
                        {
                            <option value="@mark.MarkId">@mark.MarkId - @mark.MarkName - @mark.Coefficient</option>
                        }
                    </select>
                </div>
                <div class="btn-group">
                    <button type="submit" class="btn btn-primary" style="width:150px" asp-page-handler="AddMark">Add</button>
                </div>
            </form>
            
            @if (Model.Subject.MarkAvailable.Equals(Common.AvailableStatus.Available))
            {
                <p class="text-success" style="margin-top: 30px">@Model.Subject.MarkAvailable</p>
                <form method="post">
                    <input asp-for="SelectedSubjectId" value="@Model.Subject.SubjectId" type="hidden"/>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary" style="width:150px" asp-page-handler="Apply">Apply</button>
                    </div>
                </form>
            }
            else
            {
                <p class="text-danger" style="margin-top: 30px">@Model.Subject.MarkAvailable : Sum of mark coefficient must equals to 1.</p>
                <form method="post">
                    <input asp-for="SelectedSubjectId" value="@Model.Subject.SubjectId" type="hidden"/>
                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary disabled" style="width:150px" asp-page-handler="Apply">Apply</button>
                    </div>
                </form>
            }
        }

    </div>
</div>

Project_PRN_Razor/Pages/Admin/SubjectPages/EditSubject.cshtml
@page "{subjectId:int}"
@model Project_PRN_Razor.Pages.Admin.SubjectPages.EditSubject

@{
    Layout = "Shared/_LayoutAdmin";
}

<form method="post">
    <div class="form-group">
        <label asp-for="Subject.SubjectId">Subject Id</label>
        <input asp-for="Subject.SubjectId" class="form-control" value="@Model.Subject.SubjectId" readonly>
    </div>
    <div class="form-group">
        <label asp-for="Subject.SubjectCode">Subject code</label>
        <input asp-for="Subject.SubjectCode" class="form-control" value="@Model.Subject.SubjectCode" placeholder="subject code">
    </div>
    <div class="form-group">
        <label asp-for="Subject.SubjectName">Subject name</label>
        <input asp-for="Subject.SubjectName" class="form-control" value="@Model.Subject.SubjectName" placeholder="subject name">
    </div>
    
    <div class="btn-group" style="margin-top: 50px; ">
        <button type="submit" class="btn btn-success" style="width: 150px; margin-right: 10px;" asp-page-handler="Update"> Update</button>
        <button type="submit" class="btn btn-danger" style="width: 150px" asp-page-handler="Delete"> Delete</button>
    </div>

</form>

Project_PRN_Razor/Pages/Admin/SubjectPages/Index.cshtml
@page
@using Domain.Constants
@model Project_PRN_Razor.Pages.Admin.SubjectPages.Index

@{
    Layout = "Shared/_LayoutAdmin";
}

<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">Subject List</h2>
    </div>
    <div class="col-6">
    </div>
</div>

<br/><br/>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">Subject Id</th>
        <th scope="col">Subject Code</th>
        <th scope="col">Subject Name</th>
        <th scope="col">Mark Available</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var subject in Model.Subjects)
    {
        <tr>
            <th scope="row">@subject.SubjectId</th>
            <td>@subject.SubjectCode</td>
            <td>@subject.SubjectName</td>
            @if (subject.MarkAvailable.Equals(Common.AvailableStatus.Available))
            {
                <td class="text-success">@subject.MarkAvailable</td>
            }
            else
            {
                <td class="tex-warning">@subject.MarkAvailable</td>
            }
            
            @if (subject.Deleted.Equals(Common.Status.Active))
            {
                <td class="text-success">@subject.Deleted</td>
            }
            else
            {
                <td class="text-danger">@subject.Deleted</td>
            }

            <td>
                @if (@subject.Applied)
                {
                    <a href="/Admin/SubjectPages/EditSubject/@subject.SubjectId" class="btn btn-primary disabled" >Edit</a>
                }
                else
                {
                    <a href="/Admin/SubjectPages/EditSubject/@subject.SubjectId" class="btn btn-primary">Edit</a>
                }
                <a href="/Admin/SubjectPages/DetailSubject/@subject.SubjectId" class="btn btn-primary">Detail</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<div style="margin-top: 30px;">
    <a href="/Admin/SubjectPages/CreateSubject" class="btn btn-primary">Create new Subject</a>
</div>